# Generated by Django 4.0.6 on 2022-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('AUD', 'Australian dollar'), ('CAD', 'Canadian dollar'), ('EUR', 'Euro')], default='AUD', max_length=3)),
                ('buy_sell', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], default='BUY', max_length=4)),
                ('Non_USD_amount', models.IntegerField(default=0)),
                ('USD_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
