# Generated by Django 4.0.6 on 2022-08-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='Non_USD_amount',
            new_name='Amount',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='USD_amount',
        ),
    ]
