# Generated by Django 4.0.6 on 2022-08-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_rename_non_usd_amount_trade_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='Amount',
            new_name='amount',
        ),
    ]
