# Generated by Django 4.0.6 on 2022-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_rename_amount_trade_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='currency',
            field=models.CharField(choices=[('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('NOK', 'Norwegian Krone'), ('GBP', 'Pound Sterling'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'United States Dollar')], default='AUD', max_length=3),
        ),
    ]
